import {createSlice} from '@reduxjs/toolkit';
import { IC_INFOR, IC_PHONE1, IC_PHONE2 } from '../../../assets/type';
export const recentSlide = createSlice({
  name: 'recentList',
  initialState: [
    {
      id: 1,
      name: 'Nam Design',
      sdt: '0977272123',
      missing: false,
      time: 'Hôm nay',
      icon: IC_PHONE1,
      iconInfor: IC_INFOR,
    },
    {
      id: 2,
      name: 'Dương Lê',
      sdt: '0977272123',
      missing: false,
      time: 'Hôm nay',
      icon: IC_PHONE1,
      iconInfor: IC_INFOR,
    },
    {
      id: 3,
      name: 'Thùy Trang',
      sdt: '0977272123',
      missing: false,
      time: 'Hôm nay',
      icon: IC_PHONE1,
      iconInfor: IC_INFOR,
    },
    {
      id: 4,
      name: 'Hồng Đăng',
      missing: true,
      sdt: '0977272123',
      time: 'Thứ Tư',
      iconInfor: IC_INFOR,
    },
    {
      id: 5,
      name: 'Nguyễn Tiến Nam',
      missing: true,
      sdt: '0977272123',
      time: 'Thứ Tư',
      iconInfor: IC_INFOR,
    },
    {
      id: 6,
      name: 'Bảo Ngọc',
      sdt: '0977272123',
      missing: false,
      time: 'Thứ Ba',
      icon: IC_PHONE1,
      iconInfor: IC_INFOR,
    },
    {
      id: 7,
      name: 'Thái Thùy Trang',
      sdt: '0977272123',
      missing: false,
      time: 'Thứ Hai',
      icon: IC_PHONE1,
      iconInfor: IC_INFOR,
    },
    {
      id: 8,
      name: 'Lê Ngọc Linh',
      sdt: '0977272123',
      missing: false,
      time: 'Thứ Hai',
      icon: IC_PHONE2,
      iconInfor: IC_INFOR,
    },
    {
      id: 9,
      name: 'Trần Thái Hà',
      sdt: '0977272123',
      missing: false,
      time: 'Thứ Bảy',
      icon: IC_PHONE2,
      iconInfor: IC_INFOR,
    },
    {
      id: 10,
      name: 'Nguyễn Tiến Nam',
      sdt: '0977272123',
      missing: false,
      time: 'Thứ Hai',
      icon: IC_PHONE2,
      iconInfor: IC_INFOR,
    },
  ],
  reducers: {},
});
