const initState = {
  inforList: [
    {
      id: 1,
      fullName: 'Nam Design',
      company: 'Base.vn',
      phone: '0977272160',
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar01.png'),
    },
    {
      id: 2,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Dương Lê',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar01.png'),
    },
    {
      id: 3,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Thùy Trang',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar02.png'),
    },
    {
      id: 4,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Hồng Đăng',
      company: 'OTP',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar03.png'),
    },
    {
      id: 5,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar04.png'),
    },
    {
      id: 6,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Bảo Ngọc',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar05.png'),
    },
    {
      id: 7,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Thái Thùy Trang',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar06.png'),
    },
    {
      id: 8,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Lê Ngọc Linh',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar07.png'),
    },
    {
      id: 9,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Trần Thái Hà',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar01.png'),
    },
    {
      id: 10,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../assets/images/per1.png'),
      imageAvata: require('../assets/images/avatar02.png'),
    },
  ],
};
const rootReducer = (state = initState, action) => {
  switch (action.type) {
    case 'inforList/addInfor':
      return {
        ...state,
        inforList: [...state.inforList, action.payload],
      };
    default:
      return state;
  }
};
export default rootReducer;
