const initState = {
  filter: {search: ''},
  inforList: [
    {
      id: Date.now,
      fullName: 'Nam Design',
      value: 'Nam Design',
      company: 'Base.vn',
      phone: '0977272160',
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Dương Lê',
      value: 'Dương Lê',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Thùy Trang',
      value: 'Thùy Trang',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar02.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Hồng Đăng',
      value: 'Hồng Đăng',
      company: 'OTP',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar03.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar04.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Bảo Ngọc',
      value: 'Bảo Ngọc',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar05.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Thái Thùy Trang',
      value: 'Thái Thùy Trang',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar06.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Lê Ngọc Linh',
      value: 'Lê Ngọc Linh',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar07.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Trần Thái Hà',
      value: 'Trần Thái Hà',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: Date.now,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar02.png'),
    },
  ],
  collectionList: [
    {
      id: Date.now,
      name: 'All',
      folderBig: require('../../../assets/icons/iconFolderBig.png'),
      moreOption: require('../../../assets/icons/moreOption.png'),
    },
    {
      id: Date.now,
      name: 'General',
      folderBig: require('../../../assets/icons/iconFolderBig.png'),
      moreOption: require('../../../assets/icons/moreOption.png'),
    },
    {
      id: Date.now,
      name: 'Investors',
      folderBig: require('../../../assets/icons/iconFolderBig.png'),
      moreOption: require('../../../assets/icons/moreOption.png'),
    },
    {
      id: Date.now,
      name: 'Lead',
      folderBig: require('../../../assets/icons/iconFolderBig.png'),
      moreOption: require('../../../assets/icons/moreOption.png'),
    },
    {
      id: Date.now,
      name: 'VIP',
      folderBig: require('../../../assets/icons/iconFolderBig.png'),
      moreOption: require('../../../assets/icons/moreOption.png'),
    },
  ],
};
const contactReducer = (state = initState, action) => {
  switch (action.type) {
    case 'inforList/addInfor':
      return {
        ...state,
        inforList: [...state.inforList, action.payload],
      };
    case 'search/searchContact':
      return {
        ...state,
        search: action.payload,
      };
    case 'collectionList/addCollection':
      return {
        ...state,
        collectionList: [...state.collectionList, action.payload],
      };
    default:
      return state;
  }
};
export default contactReducer;
