import {createSlice} from '@reduxjs/toolkit';
export const contentCollectionSlide = createSlice({
  name: 'contentCollectionList',
  initialState: [
    {
      id: 1,
      fullName: 'Nam Design',
      value: 'Nam Design',
      company: 'Base.vn',
      phone: '0977272160',
      batch: '',
      note: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: 2,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Dương Lê',
      note: '',
      value: 'Dương Lê',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: 3,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Thùy Trang',
      value: 'Thùy Trang',
      note: '',
      phone: '0977272123',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar02.png'),
    },
    {
      id: 4,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Hồng Đăng',
      value: 'Hồng Đăng',
      company: 'OTP',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar03.png'),
    },
    {
      id: 5,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar04.png'),
    },
    {
      id: 6,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Bảo Ngọc',
      value: 'Bảo Ngọc',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar05.png'),
    },
    {
      id: 7,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Thái Thùy Trang',
      value: 'Thái Thùy Trang',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar06.png'),
    },
    {
      id: 8,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Lê Ngọc Linh',
      value: 'Lê Ngọc Linh',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar07.png'),
    },
    {
      id: 9,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Trần Thái Hà',
      value: 'Trần Thái Hà',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar01.png'),
    },
    {
      id: 10,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: require('../../../assets/images/per1.png'),
      imageAvata: require('../../../assets/images/avatar02.png'),
    },
  ],
  reducers: {
    deleteContactOfCollection: (state, action) => {
      action.payload.forEach(item =>
        state.splice(
          state.findIndex(value => value.id === item),
          1,
        ),
      );
    },
    addContactToCollection: (state, action) => {
      state.push(...action.payload);
    },
  },
});
