import {createSlice} from '@reduxjs/toolkit';
import { IM_AVATAR01, IM_AVATAR02, IM_AVATAR03, IM_AVATAR04, IM_AVATAR05, IM_AVATAR06, IM_AVATAR07, IM_PER1, IM_PER2 } from '../../../assets/type';
export const contentCollectionSlide = createSlice({
  name: 'contentCollectionList',
  initialState: [
    {
      id: 1,
      fullName: 'Nam Design',
      value: 'Nam Design',
      company: 'Base.vn',
      phone: '0977272160',
      batch: '',
      note: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      image: IM_PER1,
      imageAvata: IM_AVATAR01,
    },
    {
      id: 2,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Dương Lê',
      note: '',
      value: 'Dương Lê',
      phone: '0977272123',
      company: 'Techcombank',
      image: IM_PER2,
      imageAvata: IM_AVATAR01,
    },
    {
      id: 3,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      fullName: 'Thùy Trang',
      value: 'Thùy Trang',
      note: '',
      phone: '0977272123',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR02,
    },
    {
      id: 4,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Hồng Đăng',
      value: 'Hồng Đăng',
      company: 'OTP',
      image: IM_PER1,
      imageAvata: IM_AVATAR03,
    },
    {
      id: 5,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR04,
    },
    {
      id: 6,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Bảo Ngọc',
      value: 'Bảo Ngọc',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR05,
    },
    {
      id: 7,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Thái Thùy Trang',
      value: 'Thái Thùy Trang',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR06,
    },
    {
      id: 8,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Lê Ngọc Linh',
      value: 'Lê Ngọc Linh',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR07,
    },
    {
      id: 9,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      note: '',
      phone: '0977272123',
      fullName: 'Trần Thái Hà',
      value: 'Trần Thái Hà',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR01,
    },
    {
      id: 10,
      batch: '',
      email: 'basenamnt@gmail.com',
      address: 'Số 12, Khuất Duy Tiến, Thanh Xuân, Hà Nội',
      DoB: '26-10-1993',
      phone: '0977272123',
      note: '',
      fullName: 'Nguyễn Tiến Nam',
      value: 'Nguyễn Tiến Nam',
      company: 'Techcombank',
      image: IM_PER1,
      imageAvata: IM_AVATAR02,
    },
  ],
  reducers: {
    deleteContactOfCollection: (state, action) => {
      action.payload.forEach(item =>
        state.splice(
          state.findIndex(value => value.id === item),
          1,
        ),
      );
    },
    addContactToCollection: (state, action) => {
      state.push(...action.payload);
    },
  },
});
